packages:
  - "apps/*"
  - "packages/*"
  - "apps/hermes/client/js"
  - "express_relay/examples/easy_lend"
  - "express_relay/sdk/js"
  - "express_relay/sdk/solidity"
  - "governance/xc_admin/packages/*"
  - "governance/pyth_staking_sdk"
  - "price_service/sdk/js"
  - "price_service/client/js"
  - "pythnet/message_buffer"
  - "target_chains/aptos/cli"
  - "target_chains/aptos/sdk/js"
  - "target_chains/cosmwasm/tools"
  - "target_chains/cosmwasm/deploy-scripts"
  - "target_chains/ethereum/contracts"
  - "target_chains/ethereum/abi_generator"
  - "target_chains/ethereum/entropy_sdk/solidity"
  - "target_chains/ethereum/sdk/js"
  - "target_chains/ethereum/sdk/solidity"
  - "target_chains/ethereum/examples/coin_flip/app"
  - "target_chains/fuel/sdk/js"
  - "target_chains/starknet/sdk/js"
  - "target_chains/sui/sdk/js"
  - "target_chains/sui/cli"
  - "target_chains/solana/sdk/js/solana_utils"
  - "target_chains/solana/sdk/js/pyth_solana_receiver"
  - "target_chains/ton/contracts"
  - "target_chains/ton/sdk/js"
  - "contract_manager"

catalog:
  "@cprussin/eslint-config": 3.0.0
  "@cprussin/jest-config": 1.4.1
  "@cprussin/prettier-config": 2.1.1
  "@cprussin/tsconfig": 3.0.1
  "@types/react-dom": npm:types-react-dom@rc
  "@types/react": npm:types-react@rc
  next: 15.0.2
  react-dom: 19.0.0-rc-603e6108-20241029
  react: 19.0.0-rc-603e6108-20241029
  framer-motion: 11.11.10
